### PR TITLE
Optuna

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
cc @tanglef

**Comment by tanglef** [comment]
I think there's something wrong with optuna (||.||_2 function in dimension 2)
Capture d’écran de 2022-07-30 17-40-30

**Comment by agramfort** [comment]
@tanglef I rebased the branch. So you may need to reset your branch here.

**Comment by agramfort** [comment]
@tanglef I've done the same + some other fixes. I'll force push here hence deleting your commit if it's ok for you

**Comment by tanglef** [comment]
Last modifications: I added CMAES in optuna as done [here](https://aetperf.github.io/2020/08/28/Minimizing-continuous-non-convex-functions-with-Optuna.html), it is indeed way more effective than RS or TPE, so to be fair with optuna we should add it

And the only modification in the figure generation file is to add  `"optuna[solver=CMAES]": "Optuna[CmAEs]",` into the `SOLVERS` dictionnary in `plot_results.py`. The actual run is not very long btw.

**Comment by tanglef** [comment]
> 
Sure ! That was my last attempt at optuna for the time :slightly_smiling_face:

**Comment by agramfort** [comment]
@tanglef I force pushed. I'll stop now.

Feel free to run this over night.

I don't see the plot_results.py script.

**Comment by tanglef** [comment]
The plot results is in the other opened PR (that should not be merged), this one could be merged after so better to keep them separate

**Comment by agramfort** [comment]
ok

**Comment by agramfort** [comment]
just to give you a flavor of where I am

Screenshot 2022-07-30 at 21 47 02

**Pull request merged**
